### ISSUE TITLE
CellProcessor process create action throws exception when it should be returning an error.

### ISSUE THREAD

**Issue by phil-kahrl** [Encapsule/holistic#16]
Build info:

"appgen": "@encapsule/holistic v0.0.46 crossroads mbeyCaeHSLyoGtX19yvb2g 
a87610edbc4589e47c01266c401f8e2abe79a053 2020-10-02T04:29:48.000Z",

An unhandled exception is being throw when calling

`actionRequest: {
        holarchy: {
          CellProcessor: {
            process: {
              create ....
`

Error thrown:

Filter [PgH0_QIhSs2c6nsw53uCjQ::OPC Act Filter] failed while performing main operation. Handled exception during controller action dispatch: apmBindiingPath is not defined

From:

https://github.com/Encapsule/holistic/blob/v0.0.46-crossroads/PACKAGES/holarchy/lib/intrinsics/CellProcessManager/ControllerAction-cpm-process-create.js#L152

**Comment by ChrisRus** [comment]
Bug in error reporting logic fixed in v0.0.46-crossroads (next test release later today).

SOURCES/LIB/holarchy/lib/intrinsics/CellProcessManager/ControllerAction-cpm-process-create.js:                errors.push(`Cannot create cell process because we cannot determine which other cell process should be assigned ownership of the proposed new cell process w/ID '${newCellProcessID}' at path '${apmBindiingPath}'.`);
