### ISSUE TITLE
AppClientDisplayAdapter should provide a ControllerAction which will allow changing the renderPath and renderContext used.

### ISSUE THREAD

**Issue by phil-kahrl** [Encapsule/holistic#9]
Build info:

"appgen": "@encapsule/holistic v0.0.46 crossroads 8Ei6heL7RE66YL0q5jkslw 450d4fe4c7db0085ce31b323b0d4eb70fff1eac6 2020-09-26T22:55:07.000Z",

Currently, the AppClientDisplayAdapter only exposes a single ControllerAction:

https://github.com/Encapsule/holistic/blob/v0.0.46-crossroads/PACKAGES/holistic-app-client-cm/AppClientDisplayAdapter/ControllerAction-react-render-client-view.js

The Controller action does not allow consumers to update the renderPath or renderContext used.  The renderPath and renderContext can be updated by writing directly to the OCD for the AppClientDisplay adapter, but that pattern in less than ideal.

**Comment by ChrisRus** [comment]
Currently, AppClientDisplayAdaptor work in @encapsule/holistic-app-client-cm is in a half-baked state pending completion of core work in @encapusle/holarchy that underpins the cell composition patterns required to realize the overall design.

We do not want to push data into the AppClientDisplayAdaptor; it's main function is to ensure that nobody initiates a new React render until the last render has completed. Effectively, this means I want AppClientDisplayAdapter to subscribe to an derived-client-app-specific AppClientDisplayDriver cell process that is ultimately responsible for:
- Providing an **observable** d2r2-format render request value
- Providing a standard mechanism by which AppClientDisplayAdaptor may read the d2r2-format render request from an AppClientDisplayDriver cell process when it observes that the last d2r2 render request it dispatched is older than the latest available AND the last render request dispatched has completed

Note that we are being intentionally vague about the internal details of what we're calling the derived-client-application-defined AppClientDisplayDriver CellModel because to AppClientDisplayAdaptor none of those details should be pertinent.

Whatever developer-defined cell is designated as the AppClientDisplayDriver will need only support the protocol above in order to gain access to AppClientDisplayAdaptor.

**Comment by phil-kahrl** [comment]
Fixed with the new Display Adapter in the alexandrite branch.
